### ISSUE TITLE
Adding orders doesn't work

### ISSUE THREAD

**Issue by dtonon** [MostroP2P/mostro#316] opened 2024-06-28 11:06 UTC
Testing on https://mostro.bilthon.dev
I created a test order, the [event](https://njump.me/nevent1qqsvwjyzyg07wzltrrgqq2hzvrz8dz3pyvclzjwgq5hwpd6wfulp6nsprpmhxue69uhhyetvv9ujumn0wdmksetjv5hxxmmdqgs8gfnkyq2mqwwywa2qyflp99qlhg4p7ghs99arvsy4a6dlnvj7lsgatsvae) has been sent to 6/8 relays, but I cannot see it anywhere (checked also using a different account). I replicated this behavior a couple of times.

**Comment by arkanoider** [comment] 2024-06-28 21:13
Hi @dtonon !

Thanks for your engagement first of all. We noticed sometimes this behaviour and we have to investigate, many times we suspect that relays are unresponsive or discarding for some weird reason events from `Mostro`, anyway usually it works.

@grunch setup a custom relay on `wss://relay.mostro.network` which should accept only event of kind 4 and 38383.

Feel free to test it and we will investigate, consider that we are basically only 3 people workin on `mostro`. Any help is appreaciated.

By the way we are from the same country and region, I know you from Nostr. :smile:

**Comment by arkanoider** [comment] 2024-07-02 17:27
Hey @dtonon ,

i forgot to say that orders are limited between 100 and 20k sats of value.
Unluckily web dev still needs to implement a popup to signal this event. Maybe your orders were too big or too small?

**Comment by dtonon** [comment] 2024-07-02 17:46
They were about 17k sats (€9).
I will try again, and post a video, maybe there is something else.

**Comment by bilthon** [comment] 2024-07-02 20:00
That's odd, I was just able to publish something. Which browser are you using? also did you check for any error logs in the console tab of the browser dev tools?

**Comment by dtonon** [comment] 2024-07-02 20:44
Macos / Chromium 123.0.6312.86 (Official Build, ungoogled-chromium) (arm64)

https://github.com/MostroP2P/mostro/assets/89577423/6c10d07e-5314-41ba-acf6-3d9fc69e71d3

**Comment by arkanoider** [comment] 2024-07-03 09:28
@bilthon could be something related to the decimal input? I don't remember how it is managed...

**Comment by dtonon** [comment] 2024-07-03 09:57
> the decimal input?

After I posted I thought exactly that, but the event is actually created, maybe is it not somehow validated when pulled?

**Comment by arkanoider** [comment] 2024-07-03 10:42
> > the decimal input?
> 
> After I posted I thought exactly that, but the event is actually created, maybe is it not somehow validated when pulled?

In the video i saw too the log of relay with 6/8 publishing, but in reality that message you're seeing above is a nip 4 message to mostro daemon that is not managing the event. Try with an order with integer you will see the broadcasted event from mostro to everybody coming after the dm nip 4

**Comment by bilthon** [comment] 2024-07-03 17:31
That's probably the culprit. I'll modify the form so that it rejects values with decimals in them.

**Comment by dtonon** [comment] 2024-07-04 14:57
I confirm that without decimal the order is created, sorry for not testing it at first.

>  I'll modify the form so that it rejects values with decimals in them.

It's fine for a quick fix, but finding the root cause might help in other areas, or reveal other related bugs. Just a suggestion :)

**Comment by grunch** [comment] 2024-07-04 15:30
> I confirm that without decimal the order is created, sorry for not testing it at first.
> 
> > I'll modify the form so that it rejects values with decimals in them.
> 
> It's fine for a quick fix, but finding the root cause might help in other areas, or reveal other related bugs. Just a suggestion :)

the root cause is mostrod doesn't work with decimals so it rejects the new order from mostro-web, it's not bug but a feature 😅

**Comment by grunch** [comment] 2024-07-10 13:34
I this is fixed on the new mostro web version, I'm closing this issue, if it's not fixed @bilthon let me know and I will re-open it again

**Closed by grunch** 2024-07-10 13:34 UTC
